acl:
  viewer:
    subscriptions:
      - 'users'
      - 'cursor'
      - 'deskshare'
      - 'meetings'
      - 'polls'
      - 'presentations'
      - 'shapes'
      - 'slides'
      - 'captions'
      - 'breakouts'
    methods:
      - 'kickUser'
      - 'listenOnlyToggle'
      - 'userLogout'
      - 'assignPresenter'
      - 'setEmojiStatus'
      - 'muteUser'
      - 'unmuteUser'
      - 'switchSlide'
      - 'switchSlideMessage'
      - 'publishVote'
      - 'sendChat'
      - 'switchSlideMessage'
  moderator:
    subscriptions:
      - 'users'
      - 'chat' 
      - 'cursor'
      - 'deskshare'
      - 'meetings'
      - 'polls'
      - 'presentations'
      - 'shapes'
      - 'slides'
      - 'captions'
      - 'breakouts'
    methods:
      - 'kickUser'
      - 'listenOnlyToggle'
      - 'userLogout'
      - 'assignPresenter'
      - 'setEmojiStatus'
      - 'muteUser'
      - 'unmuteUser'
      - 'switchSlide'
      - 'switchSlideMessage'
      - 'publishVote'
      - 'sendChat'
      - 'switchSlideMessage'
